spring:
  datasource:
    url: jdbc:mysql://localhost:3306/weaver?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: #
    open-in-view: false

  data:
    redis:
      host: localhost
      port: 6379

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    tags-sorter: alpha
    docExpansion: "none"
    persistAuthorization: true
    defaultModelsExpandDepth: -1
  use-fqn: true

oauth:
  kakako:
    url: https://kauth.kakao.com/oauth
    id: 269732da6c1f4791883a8271be0633ac
    redirect: http://localhost:3000/kakao/callback

jwt:
  secret:
    key: '!dev2024@-backend-jwt-secretkey2024!@-38523084793tdjf9328e83gcweg893213ce2r43t24'
